title: Nonprofit Data Science Toolkit
author: lecy
email: jdlecy@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  An introduction to the data science ecosystem for nonprofit scholarship

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
