title: Nonprofit Data Science Toolkit
author: lecy
email: jdlecy@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
